name: Student Registration

on:
  schedule:
    - cron: '30 3 * * *'   # 9:00 AM IST
  workflow_dispatch:

jobs:

  run-test:

    runs-on: windows-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Run Student Registration
        run: mvn test -Dheadless=true -Dtest=StudentRegistrationTest