name: Student Registration

on:
  schedule:
    - cron: '*/2 * * * *'   # every 2 minutes for testing
  workflow_dispatch:

jobs:

  run-test:

    runs-on: windows-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Run Student Registration
        run: mvn test -Dheadless=true -Dtest=StudentRegistrationTest

      - name: Upload Screenshot
        uses: actions/upload-artifact@v4
        with:
              name: registration-proof
              path: screenshots/

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true

          username: ${{ secrets.GMAIL_USER }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}

          subject: Customer Portal Registration Success

          to: Amarteja.Chennu@infinite.com
          from: ${{ secrets.GMAIL_USER }}

          body: |
            ✅ Customer Portal Registration Success

            Execution Time: Automated GitHub Run

            Status: SUCCESS

            Please find the registration confirmation screenshot attached for reference.

            Regards,
            QA Automation Suite

          attachments: screenshots/congratulations.png